### PR TITLE
fixing colors for contrast

### PR DESCRIPTION
**Pull request by mgifford**
Cheeky, but good to get it right.

http://contrast-finder.tanaguru.com/result.html?foreground=%23e00000&background=%23eeeeee&ratio=4.5

### CODE REVIEW

**Comment by cehfisher** [comment]
Hmm not sure what you are checking @mgifford...maybe the darker overlay where the color name is printed. The source code confirms the background color listed is correct at #e00000.
cherry

**Comment by cehfisher** [comment]
@mgifford are you talking about the red logo on the gray background not meeting the correct ratio for contrast? that is the only place red is on gray that I can remember. If so, I think I'd like to make the gray lighter, since the logo is an SVG file and a tiny bit more difficult to update.

**Comment by mgifford** [comment]
I think I may have been doing this too quickly.  The problem is #e00000. From WAVE I thought it was against the white background, but might just be against the light grey (#eeeeee). I wasn't really concerned with the logo, but the numbered text on the side. 

Sometimes SVG files are trivially easy to modify the color. All depends on how they are built. But it's a PNG right site-logo.png?

screen shot 2017-04-28 at 9 58 08 am

Sorry for the DrupalCon confusion.

**Comment by cehfisher** [comment]
thanks @mgifford for the PR! I'm finally coming out of my DrupalCon haze, so can look at this more closely.

**Comment by mgifford** [comment]
This is good..  Hard to focus while at a conference at the best of times.

**Pull request merged**
