### PR TITLE
Add guidance on relative units.

### LINKED ISSUE #160: Font size examples
Using rem vs pt vs vw examples of what is best for browser resizing (ex. https://madebymike.com.au/writing/fluid-type-calc-examples)

### PR DESCRIPTION
**Pull request by kendrick**
Let me know what you think—more/less detail? Other typographic issues I could touch on?

(Fixes #160.)

### CODE REVIEW

**Comment by scottaohara** [comment]
going to merge this in. Definitely does good in fleshing out that topic. Feel free to expand on any other type (or other) related topics :)

**Comment by cehfisher** [comment]
hey @kendrick just a quick note that the typography _component_ needs to be changed, not the style guide HTML file. The issue is that running `npm run gulp` will override your text changes in the HTML file since those pages are dynamically created.  I will push up a PR in a few minutes so you can see the difference. Thanks for the updates though!

**Comment by cehfisher** [comment]
ok so the file to change is: `src/global/utils/_typography.scss`
then run a `npm run gulp` and the HTML file and associated `dist` version is created. The PR #182 shows the changes, plus the demo update. thanks again @kendrick for your help on the content!

**Comment by kendrick** [comment]
@cehfisher Thanks for the pointer, I didn't dig deep enough into the build setup! 😑

**Pull request merged**
