### PR TITLE
Update page title to include 'a11y'

### PR DESCRIPTION
**Pull request by shrop**
In this improvement, I think it helps to show the full document title in browser tabs.

Thanks!

### CODE REVIEW

**Comment by cehfisher** [comment]
hey @shrop! thanks for this update...two things to note though:
1. I think it should be capitalized A11Y to be consistent with other parts of the site.
2. typically changes are made in the `src` folder for KSS, then the compiler is run (ex. `npm run gulp`) then these changes are copied over to the `dist` folder automatically. i can commit these changes, but they would disappear with the next compile. :(

Let me know if you want me to make the changes for you or if you want to submit a new branch. Thanks!

**Comment by shrop** [comment]
yeah, I can get one up there tonight. Love to learn the structure/process. Thanks!

**Comment by cehfisher** [comment]
here are the steps I take to compile:
- Navigate to: themes/custom/a11y_style_guide
- nvm install stable (only need to do once)
- nvm use
- nvm install (only need to do once)
- Change/add some code **I should really note that the code should be changed in the `src` folder here**
- nvm run gulp (there are other micro-commands as well, but this runs all of the compilers)

I don't think I am missing any steps, but when you go through them let me know if you get stuck. I may have missed some things and need to update the instructions a bit for the non-front-endy people. thanks again @shrop :)

**Comment by shrop** [comment]
@cehfisher I was looking at this a bit and the getting started guide on in the main readme says to change directory to "themes/custom/a11y_style_guide". I am not seeing that in there. Which folder should I navigate to and are those commands in the readme still accurate?

**Comment by cehfisher** [comment]
@shrop I'm running my local through DrupalVM (https://www.drupalvm.com) so I added a themes/custom folder and added the a11y style guide content to that (much like client based projects), so yes, you are correct that I need to update the readme a bit.

After initially creating this project to be Drupal based, I realized that it would be potentially more useful being CMS agnostic, so I've been taking out some pieces as I go. I definitely need to run through installing this w/o Drupal as the base and see if I can update the instructions a bit. If you have any time this week to go through the steps together, it might be helpful.

**Comment by shrop** [comment]
@cehfisher I am definitely game to work through this and can help document the project to help out!

**Pull request merged**
